package main

import (
	"bytes"
	"fmt"
	"io/ioutil"
	"log"
	"net/http"

	msgpack "github.com/vmihailenco/msgpack/v5"
)

func main() {
	url := "http://localhost:9090/todos"
	method := "POST"

	msg, err := msgpack.Marshal(&Task{Task: "taskxxx"})
	if err != nil {
		log.Panic(err)
	}

	payload := bytes.NewReader(msg)

	client := &http.Client{}
	req, err := http.NewRequest(method, url, payload)
	if err != nil {
		log.Panic(err)
	}
	req.Header.Add("Content-Type", "application/msgpack")

	res, err := client.Do(req)
	if err != nil {
		log.Panic(err)
	}
	defer res.Body.Close()

	body, err := ioutil.ReadAll(res.Body)
	if err != nil {
		log.Panic(err)
	}
	fmt.Println(string(body))
}

// Generated by https://quicktype.io

type Task struct {
	Task string `json:"task"`
}